# Generated by Django 5.1 on 2024-12-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_unit_variation_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
