# Generated by Django 5.1 on 2024-12-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_variation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductVariationStock',
        ),
    ]
