# Generated by Django 5.1 on 2024-12-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_remove_purchaseproduct_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='extra_costs',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_number',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
