# Generated by Django 5.1 on 2024-12-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_remove_purchase_extra_costs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='extra_costs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
