# Generated by Django 5.1 on 2024-12-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchase_extra_costs_alter_purchase_purchase_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
