# Generated by Django 5.1 on 2024-12-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_purchase_stock_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='stock_updated',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
