# Generated by Django 5.1 on 2024-12-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_alter_purchase_stock_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='is_paid',
        ),
    ]
