# Generated by Django 5.1 on 2024-12-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_remove_purchase_is_paid'),
        ('store', '0012_productimage_variation_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='variation',
            field=models.ManyToManyField(to='store.variation'),
        ),
    ]
