# Generated by Django 5.1 on 2025-02-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reset_token_used',
            field=models.BooleanField(default=False),
        ),
    ]
