# Generated by Django 5.1 on 2024-09-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_session_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
